import type { Metadata } from 'next';
import { jost } from '@/app/ui/fonts';
import '../styles/index.scss';
import { NavBar } from '@/widgets/NavBar';
import { Footer } from '@/widgets/Footer';


export const metadata: Metadata = {
    title: 'SalsaBrest',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const bgFirst = 'var(--bg-color)';
    
    return (
        <html lang='ru'>
            <body>
                <main className={`${jost.className} app`}> 
                    <NavBar />
                    {children}
                    <Footer backgroundColor={bgFirst}/>
                </main>
                <div id="modal-root"></div>
            </body>
        </html>
    );
}
